<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup Label="Common">
    <PackageVersion Include="Microsoft.Bcl.HashCode" Version="1.0.0" />
    <PackageVersion Include="System.ValueTuple" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageVersion Include="Grpc.Tools" Version="2.81.1" />
    <PackageVersion Include="Meziantou.Polyfill" Version="1.0.151" />
  </ItemGroup>

  <ItemGroup Label="Analyzers">
    <GlobalPackageReference Include="Altemiq.DotNet.CodingStandard" Version="1.0.296" />
  </ItemGroup>

  <ItemGroup Label="Build">
    <GlobalPackageReference Include="Altemiq.SemanticVersioning.MSBuild" Version="10.0.3" />
  </ItemGroup>

</Project>
