<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net6.0;netstandard2.1;netstandard2.0</TargetFrameworks>
    <PackageId>$(RootNamespace)</PackageId>
    <RootNamespace>$(RootNamespace.Replace('.Core', ''))</RootNamespace>
    <AssemblyName>$(RootNamespace)</AssemblyName>
    <MeziantouPolyfill_IncludedPolyfills>
      $(MeziantouPolyfill_IncludedPolyfills)|
      M:System.ArgumentNullException.ThrowIfNull(System.Object,System.String)|
      M:System.Enum.Parse``1(System.String,System.Boolean)|
      M:System.String.Replace(System.String,System.String,System.StringComparison)|
      T:System.Diagnostics.CodeAnalysis.NotNullAttribute|
      T:System.Runtime.CompilerServices.CallerArgumentExpressionAttribute|
    </MeziantouPolyfill_IncludedPolyfills>
    <GenerateStronglyTypedResources>true</GenerateStronglyTypedResources>
  </PropertyGroup>

  <PropertyGroup Label="Packaging">
    <Description>$(RootNamespace) is a lightweight ADO.NET provider for SQLite. This package does not include a copy of the native SQLite library.</Description>
    <PackageTags>$(PackageTags) Data SQLite</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Meziantou.Polyfill">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="*.xml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite.Core" VersionOverride="$(VerMicrosoft_Data_Sqlite)" />
  </ItemGroup>

</Project>
