<Project>

  <PropertyGroup Condition=" $([MSBuild]::GetTargetFrameworkIdentifier($(TargetFramework))) == '.NETFramework' ">
    <_Platform>$([System.Runtime.InteropServices.RuntimeInformation]::ProcessArchitecture)</_Platform>
    <Platform>$(_Platform.ToLower())</Platform>
    <RuntimeIdentifier>win-$(Platform)</RuntimeIdentifier>
    <PlatformTarget>$(Platform)</PlatformTarget>
  </PropertyGroup>

</Project>
