<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net6.0;netstandard2.1;netstandard2.0</TargetFrameworks>
    <Description>$(Description) Data GeoPackage Assembly</Description>
    <PackageTags>$(PackageTags) Data GeoPackage</PackageTags>
    <PackageId>$(RootNamespace)</PackageId>
    <RootNamespace>$(RootNamespace.Replace('.Core', ''))</RootNamespace>
    <AssemblyName>$(RootNamespace)</AssemblyName>
    <MeziantouPolyfill_IncludedPolyfills>
      $(MeziantouPolyfill_IncludedPolyfills)|
      M:System.String.CopyTo(System.Span{System.Char})|
      M:System.String.Create(System.IFormatProvider,System.Runtime.CompilerServices.DefaultInterpolatedStringHandler@)|
      M:System.String.TryCopyTo(System.Span{System.Char})|
      T:System.Diagnostics.CodeAnalysis.DoesNotReturnAttribute|
      T:System.Diagnostics.CodeAnalysis.NotNullWhenAttribute|
      T:System.Index|
      T:System.Range|
      T:System.Runtime.CompilerServices.DefaultInterpolatedStringHandler|
      T:System.Runtime.CompilerServices.InterpolatedStringHandlerArgumentAttribute|
      T:System.Runtime.CompilerServices.InterpolatedStringHandlerAttribute|
    </MeziantouPolyfill_IncludedPolyfills>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Meziantou.Polyfill">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Data.Geometry\Data.Geometry.csproj" />
    <ProjectReference Include="..\Data.Sqlite.Core\Data.Sqlite.Core.csproj" />
  </ItemGroup>

</Project>
