<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>$(RootNamespace.Replace('.Geometry', ''))</RootNamespace>
    <MeziantouPolyfill_IncludedPolyfills>
      $(MeziantouPolyfill_IncludedPolyfills)|
      M:System.ArgumentNullException.ThrowIfNull(System.Object,System.String)|
      M:System.ArgumentOutOfRangeException.ThrowIfLessThan``1(``0,``0,System.String)|
      T:System.Diagnostics.CodeAnalysis.NotNullAttribute|
      T:System.Runtime.CompilerServices.CallerArgumentExpressionAttribute|
      T:System.Runtime.CompilerServices.IsExternalInit|
    </MeziantouPolyfill_IncludedPolyfills>
    <GenerateStronglyTypedResources>true</GenerateStronglyTypedResources>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Meziantou.Polyfill">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Geometry\Geometry.csproj" />
  </ItemGroup>

  <ItemGroup Condition=" ($([MSBuild]::GetTargetFrameworkIdentifier($(TargetFramework))) == '.NETStandard' and $([MSBuild]::VersionEquals($([MSBuild]::GetTargetFrameworkVersion($(TargetFramework))), 2.0))) or ($([MSBuild]::GetTargetFrameworkIdentifier($(TargetFramework))) == '.NETFramework') ">
    <PackageReference Include="System.Memory" VersionOverride="4.5.0" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Altemiq.Geometry" />
  </ItemGroup>

</Project>
