<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net7.0;netcoreapp3.1;netstandard2.1;netstandard2.0;net461</TargetFrameworks>
    <Description>$(Description) Data GeoPackage Assembly</Description>
    <PackageTags>$(PackageTags) Data GeoPackage</PackageTags>
    <RootNamespace>$(Company).$(MSBuildProjectName)</RootNamespace>
    <PolySharpIncludeGeneratedTypes>
      System.Diagnostics.CodeAnalysis.DoesNotReturnAttribute;
      System.Diagnostics.CodeAnalysis.NotNullWhenAttribute;
      System.Index;
      System.Range;
    </PolySharpIncludeGeneratedTypes>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="PolySharp">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Data.Geometry\Data.Geometry.csproj" />
    <ProjectReference Include="..\Data.Sqlite\Data.Sqlite.csproj" />
  </ItemGroup>

</Project>
