<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net9.0;net8.0</TargetFrameworks>
    <TargetFrameworks Condition="$([System.OperatingSystem]::IsWindows())">$(TargetFrameworks);net472</TargetFrameworks>
    <NoWarn>$(NoWarn);NETSDK1206</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="TUnit" />
    <PackageReference Include="SpatiaLite" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\IO.Geometry.Spatialite.Core\IO.Geometry.Spatialite.Core.csproj" />
  </ItemGroup>

</Project>
