<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;netstandard2.0;net461</TargetFrameworks>
    <PolySharpIncludeGeneratedTypes>
      System.Runtime.CompilerServices.CallerArgumentExpressionAttribute;
      System.Runtime.CompilerServices.IsExternalInit;
    </PolySharpIncludeGeneratedTypes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PolySharp">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Text.GeoJson\Text.GeoJson.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="System.Text.Json;System.Text.Json.Serialization" />
    <Using Remove="System.Net.Http" />
  </ItemGroup>

</Project>
