<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;netstandard2.0;net461</TargetFrameworks>
    <MeziantouPolyfill_IncludedPolyfills>
      $(MeziantouPolyfill_IncludedPolyfills)|
      M:System.Enum.Parse``1(System.String)|
      T:System.Runtime.CompilerServices.CallerArgumentExpressionAttribute|
      T:System.Runtime.CompilerServices.CompilerFeatureRequiredAttribute|
      T:System.Runtime.CompilerServices.IsExternalInit|
      T:System.Runtime.CompilerServices.RequiredMemberAttribute|
    </MeziantouPolyfill_IncludedPolyfills>
  </PropertyGroup>

  <PropertyGroup Label="Packaging">
    <Description>[STAC](https://stacspec.org) serialization for geospatial data.</Description>
    <PackageTags>$(PackageTags) GeoJSON STAC Geospatial JSON Format</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Meziantou.Polyfill">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Text.GeoJson\Text.GeoJson.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="System.Text.Json;System.Text.Json.Serialization" />
    <Using Remove="System.Net.Http" />
  </ItemGroup>

</Project>
