<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;netstandard2.0;net461</TargetFrameworks>
    <MeziantouPolyfill_IncludedPolyfills>
      $(MeziantouPolyfill_IncludedPolyfills)|
      M:System.ArgumentNullException.ThrowIfNull(System.Object,System.String)|
      M:System.String.IndexOf(System.Char,System.StringComparison)|
      T:System.Diagnostics.CodeAnalysis.DoesNotReturnAttribute|
      T:System.Diagnostics.CodeAnalysis.NotNullAttribute|
      T:System.Diagnostics.CodeAnalysis.NotNullWhenAttribute|
      T:System.Index|
      T:System.Range|
      T:System.Runtime.CompilerServices.CallerArgumentExpressionAttribute|
      T:System.Runtime.CompilerServices.IsExternalInit|
    </MeziantouPolyfill_IncludedPolyfills>
    <LangVersion>preview</LangVersion>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Meziantou.Polyfill">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Data.Dbf\Data.Dbf.csproj" />
    <ProjectReference Include="..\Data.Geometry\Data.Geometry.csproj" />
    <ProjectReference Include="..\Geometry\Geometry.csproj" />
  </ItemGroup>

</Project>
