<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net7.0;netstandard2.1;netstandard2.0</TargetFrameworks>
    <MeziantouPolyfill_IncludedPolyfills>
      $(MeziantouPolyfill_IncludedPolyfills)|
      M:System.Double.TryParse(System.ReadOnlySpan{System.Char},System.Globalization.NumberStyles,System.IFormatProvider,System.Double@)|
      M:System.Text.Encoding.GetBytes(System.ReadOnlySpan{System.Char},System.Span{System.Byte})|
      M:System.Text.Encoding.GetString(System.ReadOnlySpan{System.Byte})|
      T:System.Diagnostics.CodeAnalysis.DoesNotReturnAttribute|
      T:System.Diagnostics.CodeAnalysis.NotNullWhenAttribute|
      T:System.Index|
      T:System.Range|
    </MeziantouPolyfill_IncludedPolyfills>
    <!--<GenerateStronglyTypedResources>true</GenerateStronglyTypedResources>-->
  </PropertyGroup>

  <PropertyGroup Label="Packaging">
    <Description>Well-known text coordinate reference system reader inspired by System.Text.Json.</Description>
    <PackageTags>$(PackageTags) Text WKT CRS Coordinate System</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Meziantou.Polyfill">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <!--<ItemGroup Condition=" $([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'netstandard2.0')) and !$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'netstandard2.1')) ">
    <PackageReference Include="Microsoft.Bcl.HashCode" VersionOverride="1.0.0" />
    <PackageReference Include="System.Memory" VersionOverride="4.5.0" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" VersionOverride="4.5.0" />
  </ItemGroup>-->

  <ItemGroup Condition=" $([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'netstandard2.0')) and !$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'netstandard2.1')) ">
    <PackageReference Include="System.Memory" VersionOverride="4.5.0" />
  </ItemGroup>

</Project>