<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net7.0;netstandard2.1;netstandard2.0</TargetFrameworks>
    <MeziantouPolyfill_IncludedPolyfills>
      $(MeziantouPolyfill_IncludedPolyfills)|
      M:System.ArgumentNullException.ThrowIfNull(System.Object,System.String)|
      M:System.ArgumentOutOfRangeException.ThrowIfGreaterThan``1(``0,``0,System.String)|
      M:System.ArgumentOutOfRangeException.ThrowIfLessThan``1(``0,``0,System.String)|
      M:System.Double.TryParse(System.ReadOnlySpan{System.Char},System.Globalization.NumberStyles,System.IFormatProvider,System.Double@)|
      M:System.Enum.TryParse``1(System.ReadOnlySpan{System.Char},System.Boolean,``0@)|
      M:System.IO.Stream.Write(System.ReadOnlySpan{System.Byte})|
      M:System.ObjectDisposedException.ThrowIf(System.Boolean,System.Object)|
      M:System.Text.Encoding.GetByteCount(System.ReadOnlySpan{System.Char})|
      M:System.Text.Encoding.GetBytes(System.ReadOnlySpan{System.Char},System.Span{System.Byte})|
      M:System.Text.Encoding.GetCharCount(System.ReadOnlySpan{System.Byte})|
      M:System.Text.Encoding.GetChars(System.ReadOnlySpan{System.Byte},System.Span{System.Char})|
      M:System.Text.Encoding.GetString(System.ReadOnlySpan{System.Byte})|
      T:System.Diagnostics.CodeAnalysis.DoesNotReturnAttribute|
      T:System.Diagnostics.CodeAnalysis.DoesNotReturnIfAttribute|
      T:System.Diagnostics.CodeAnalysis.NotNullAttribute|
      T:System.Diagnostics.CodeAnalysis.NotNullWhenAttribute|
      T:System.Diagnostics.StackTraceHiddenAttribute|
      T:System.Index|
      T:System.Range|
      T:System.Runtime.CompilerServices.CallerArgumentExpressionAttribute|
      T:System.Runtime.CompilerServices.IsExternalInit|
      M:System.String.Create``1(System.Int32,``0,System.Buffers.SpanAction{System.Char,``0})|
    </MeziantouPolyfill_IncludedPolyfills>
    <!--<GenerateStronglyTypedResources>true</GenerateStronglyTypedResources>-->
  </PropertyGroup>

  <PropertyGroup Label="Packaging">
    <Description>Well-known text coordinate reference system reader inspired by System.Text.Json.</Description>
    <PackageTags>$(PackageTags) Text WKT CRS Coordinate System</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Meziantou.Polyfill">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup Condition=" $([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'netstandard2.0')) and !$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'netstandard2.1')) ">
    <PackageReference Include="System.Buffers" VersionOverride="4.5.0" />
    <PackageReference Include="System.Memory" VersionOverride="4.5.0" />
  </ItemGroup>

</Project>