<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;netstandard2.0;net461</TargetFrameworks>
    <MeziantouPolyfill_IncludedPolyfills>
      $(MeziantouPolyfill_IncludedPolyfills)|
      T:System.Runtime.CompilerServices.CompilerFeatureRequiredAttribute|
      T:System.Runtime.CompilerServices.IsExternalInit|
      T:System.Runtime.CompilerServices.RequiredMemberAttribute|
    </MeziantouPolyfill_IncludedPolyfills>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Meziantou.Polyfill">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Text.Json" VersionOverride="6.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Geometry\Geometry.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="System.Text.Json;System.Text.Json.Serialization" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="$(AssemblyName).Stac" />
  </ItemGroup>

</Project>
