<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0;net8.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Data.Dbf\Data.Dbf.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\data\shp\*.dbf;..\data\shp\*.dbt;..\data\shp\*.ndx" Link="Data\%(FileName)%(Extension)" />
  </ItemGroup>

</Project>
