<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;netstandard2.0;net461</TargetFrameworks>
    <Description>$(Description)
      based off https://support.esri.com/en/white-paper/279
      with PRJ definitions from https://github.com/Esri/projection-engine-db-doc</Description>
    <MeziantouPolyfill_IncludedPolyfills>
      $(MeziantouPolyfill_IncludedPolyfills)|
      M:System.ArgumentNullException.ThrowIfNull(System.Object,System.String)|
      M:System.IO.Stream.Read(System.Span{System.Byte})|
      M:System.IO.Stream.Write(System.ReadOnlySpan{System.Byte})|
      T:System.Diagnostics.CodeAnalysis.DoesNotReturnAttribute|
      T:System.Diagnostics.CodeAnalysis.MaybeNullAttribute|
      T:System.Diagnostics.CodeAnalysis.NotNullAttribute|
      T:System.Diagnostics.CodeAnalysis.NotNullWhenAttribute|
      T:System.Index|
      T:System.Range|
      T:System.Runtime.CompilerServices.CallerArgumentExpressionAttribute|
      T:System.Runtime.CompilerServices.CompilerFeatureRequiredAttribute|
      T:System.Runtime.CompilerServices.IsExternalInit|
      T:System.Runtime.CompilerServices.RequiredMemberAttribute|
    </MeziantouPolyfill_IncludedPolyfills>
    <GenerateStronglyTypedResources>true</GenerateStronglyTypedResources>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Meziantou.Polyfill">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Text.Json" VersionOverride="6.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Data.Dbf\Data.Dbf.csproj" />
    <ProjectReference Include="..\IO.Geodesy\IO.Geodesy.csproj" />
    <ProjectReference Include="..\IO.Geometry\IO.Geometry.csproj" />
  </ItemGroup>

  <Target Name="_DownloadJsonDefinitions"
          BeforeTargets="DispatchToInnerBuilds">
    <DownloadFile SourceUrl="https://github.com/Esri/projection-engine-db-doc/raw/refs/heads/main/json/pe_list_geogcs.json" DestinationFolder="$(IntermediateOutputPath)" SkipUnchangedFiles="true">
      <Output TaskParameter="DownloadedFile" ItemName="_EmbeddedResourceToZip"/>
    </DownloadFile>
    <DownloadFile SourceUrl="https://github.com/Esri/projection-engine-db-doc/raw/refs/heads/main/json/pe_list_projcs.json" DestinationFolder="$(IntermediateOutputPath)" SkipUnchangedFiles="true">
      <Output TaskParameter="DownloadedFile" ItemName="_EmbeddedResourceToZip"/>
    </DownloadFile>

    <GZip Files="@(_EmbeddedResourceToZip)" ProjectName="$(MSBuildProjectName)">
      <Output ItemName="_ZippedEmbeddedResource" TaskParameter="Result" />
    </GZip>

    <ItemGroup>
      <_InnerBuildProjects Update="@(_InnerBuildProjects)" AdditionalProperties="%(AdditionalProperties);ZippedResourcePath=$(IntermediateOutputPath)" />
    </ItemGroup>
  </Target>
  
  <Target Name="_AddEmbeddedResources"
          BeforeTargets="CheckForDuplicateItems">
    <PropertyGroup>
      <ZippedResourcePath Condition=" '$(ZippedResourcePath)' == '' ">$(BaseIntermediateOutputPath)\$(Configuration)</ZippedResourcePath>
    </PropertyGroup>
    
    <ItemGroup>
      <_ZippedEmbeddedResources Include="$(ZippedResourcePath)\pe_list_*.json.gz" />
      <EmbeddedResource Include="@(_ZippedEmbeddedResources)" LogicalName="$(RootNamespace).%(FileName)%(Extension)" />
    </ItemGroup>
  </Target>

  <ItemGroup>
    <Using Include="Altemiq.Geometry" />
  </ItemGroup>

  <Import Project="$(MSBuildProjectDirectory)\ZipResources.targets" />

</Project>
