<Project>

  <UsingTask TaskName="GZip" TaskFactory="RoslynCodeTaskFactory" AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.Core.dll">
    <ParameterGroup>
      <ProjectName Required="true" />
      <Files ParameterType="Microsoft.Build.Framework.ITaskItem[]" Required="true" />
      <Result ParameterType="Microsoft.Build.Framework.ITaskItem[]" Output="true" />
    </ParameterGroup>
    <Task>
      <Using Namespace="System.IO" />
      <Using Namespace="System.IO.Compression" />
      <Code Type="Fragment" Language="cs">
<![CDATA[
if (Files.Length > 0)
{
    Result = new TaskItem[Files.Length];
    for (var i = 0; i < Files.Length; i++)
    {
        var item = Files[i];
        var sourcePath = item.GetMetadata("FullPath");
        var sourceItemSpec = item.ItemSpec;

        var destinationSuffix = ".gz";
        var destinationPath = sourcePath + destinationSuffix;
        var destinationItemSpec = sourceItemSpec + destinationSuffix;

        if (!File.Exists(destinationItemSpec))
        {
            Log.LogMessage(MessageImportance.Normal, ProjectName + " -> EmbeddedResource Src : " + sourceItemSpec);

            using (var sourceStream = File.OpenRead(sourcePath))
            {
                using (var destinationStream = File.OpenWrite(destinationPath))
                {
                    using (var destinationGZip = new GZipStream(destinationStream, CompressionLevel.Optimal))
                    {
                        sourceStream.CopyTo(destinationGZip);
                    }
                }
            }
        }

        var destinationItem = new TaskItem(destinationItemSpec);

        Log.LogMessage(MessageImportance.Normal, ProjectName + " -> EmbeddedResource GZip: " + destinationItem.ItemSpec);

        Result[i] = destinationItem;
    }
}
]]>
      </Code>
    </Task>
  </UsingTask>

</Project>
