<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net9.0;net8.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\IO.Spatial\IO.Spatial.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\*" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Altemiq.Geometry" />
  </ItemGroup>

</Project>
