<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net6.0;netstandard2.1;netstandard2.0</TargetFrameworks>
    <PackageId>$(RootNamespace)</PackageId>
    <RootNamespace>$(RootNamespace.Replace('.Core', ''))</RootNamespace>
    <AssemblyName>$(RootNamespace)</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <MeziantouPolyfill_IncludedPolyfills>
      $(MeziantouPolyfill_IncludedPolyfills)|
      M:System.Enum.Parse``1(System.String,System.Boolean)|
      M:System.Enum.IsDefined``1(``0)|
      T:System.Diagnostics.CodeAnalysis.AllowNullAttribute|
      T:System.Diagnostics.CodeAnalysis.NotNullIfNotNullAttribute|
    </MeziantouPolyfill_IncludedPolyfills>
    <GenerateStronglyTypedResources>true</GenerateStronglyTypedResources>
  </PropertyGroup>

  <PropertyGroup Label="Packaging">
    <Description>$(RootNamespace) is a lightweight ADO.NET provider for SpatiaLite. This package does not include a copy of the native SpatiaLite library.</Description>
    <PackageTags>$(PackageTags) Data SQLite SpatiaLite</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Altemiq.Runtime" VersionOverride="1.1.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyModel" VersionOverride="6.0.0" />
    <PackageReference Include="Meziantou.Polyfill">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Data.Sqlite.Core\Data.Sqlite.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx" Generator="" />
  </ItemGroup>

</Project>
