<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net6.0;netstandard2.1;netstandard2.0</TargetFrameworks>
    <Description>$(Description) Geometry SpatiaLite Assembly</Description>
    <PackageTags>$(PackageTags) Geometry SpatiaLite</PackageTags>
    <PackageId>$(RootNamespace)</PackageId>
    <RootNamespace>$(RootNamespace.Replace('.Core', ''))</RootNamespace>
    <AssemblyName>$(RootNamespace)</AssemblyName>
    <MeziantouPolyfill_IncludedPolyfills>
      $(MeziantouPolyfill_IncludedPolyfills)|
      M:System.IO.Stream.Write(System.ReadOnlySpan{System.Byte})|
      T:System.Diagnostics.CodeAnalysis.DoesNotReturnAttribute|
      T:System.Diagnostics.CodeAnalysis.MaybeNullAttribute|
      T:System.Diagnostics.CodeAnalysis.NotNullIfNotNullAttribute|
      T:System.Diagnostics.CodeAnalysis.NotNullWhenAttribute|
      T:System.Index|
      T:System.Range|
    </MeziantouPolyfill_IncludedPolyfills>
    <GenerateStronglyTypedResources>true</GenerateStronglyTypedResources>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Meziantou.Polyfill">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Data.Geometry\Data.Geometry.csproj" />
    <ProjectReference Include="..\Data.Spatialite.Core\Data.Spatialite.Core.csproj" />
  </ItemGroup>

</Project>
