<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('$(MSBuildThisFileName)$(MSBuildThisFileExtension)', '$(MSBuildThisFileDirectory)../'))" />

  <PropertyGroup>
    <VerMicrosoft_Data_Sqlite>6.0.0</VerMicrosoft_Data_Sqlite>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$([MSBuild]::EnsureTrailingSlash('$(MSBuildProjectDirectory)'))icon.png" Pack="true" PackagePath="\" Condition="Exists('$([MSBuild]::EnsureTrailingSlash($(MSBuildProjectDirectory)))icon.png')" />
    <None Include="$([MSBuild]::EnsureTrailingSlash('$(MSBuildProjectDirectory)'))README.md" Pack="true" PackagePath="\" Condition="Exists('$([MSBuild]::EnsureTrailingSlash($(MSBuildProjectDirectory)))README.md')" />
  </ItemGroup>
  
  <PropertyGroup Label="Packaging">
    <Authors>rsking;altemiq</Authors>
    <Description>||PlaceHolder||</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

</Project>
