<Project>

  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Description>$(Description) Data SpatiaLite Assembly</Description>
    <PackageTags>$(PackageTags) Data SpatiaLite</PackageTags>
    <MinClientVersion>3.6</MinClientVersion>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <IncludeSymbols>false</IncludeSymbols>
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
    <DisableSemanticVersioning>true</DisableSemanticVersioning>
    <GetVersionFrom>..\Data.Spatialite.Core\Data.Spatialite.Core.csproj</GetVersionFrom>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" VersionOverride="$(VerMicrosoft_Data_Sqlite)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="$(GetVersionFrom)" />
  </ItemGroup>

  <ItemGroup>
    <None Include="lib\**\*">
      <Pack>True</Pack>
      <PackagePath>lib</PackagePath>
    </None>
  </ItemGroup>

  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />

  <Target Name="Compile" />
  <Target Name="CopyFilesToOutputDirectory" />

</Project>
