name: .NET Core

on:
  push:
    branches:
      - main
    paths-ignore:
      - docs/**
      - .github/workflows/docs.yml
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_MULTILEVEL_LOOKUP: false

    steps:
    - uses: actions/checkout@v5

    # Install the .NET workloads
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.x
          
    - name: Run local/dotnet-build@v1
      run: dotnet build

    - name: Run local/dotnet-test@v1
      run: >
        dotnet test
        --no-build
        --logger GitHubActions
        --
        --results-directory ${{ github.workspace }}/coverage/results
        --coverage
        --coverage-output-format cobertura

    - uses: danielpalme/ReportGenerator-GitHub-Action@v5
      with:
        reports: ${{ github.workspace }}/coverage/results/*.cobertura.xml
        targetdir: ${{ github.workspace }}/coverage/reports
        reporttypes: HtmlInline;Cobertura;MarkdownSummaryGithub
        verbosity: Verbose

    - name: Run local/set-test-summary@v1
      run: cat '${{ github.workspace }}/coverage/reports/SummaryGithub.md' >> $GITHUB_STEP_SUMMARY

    - uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: ${{ github.workspace }}/coverage/reports

  create-nuget:
    runs-on: ubuntu-latest

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_MULTILEVEL_LOOKUP: false
      Configuration: Release

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0 # for versioning

    # Install the .NET workloads
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Run local/dotnet-build@v1
      run: dotnet build

    - name: Run local/get-suffix@v1
      id: suffix
      run: |
        suffix=alpha
        if [ ${{ github.event_name }} == push ];
        then
          suffix=beta;
        fi

        echo "value=$suffix" >> $GITHUB_OUTPUT
      
    - name: Run local/dotnet-pack@v1
      run: dotnet pack --output ${{ github.workspace }}/nupkg -property:ComputeSemanticVersion=true -property:SemanticVersionOutputPath=${{ github.workspace }}/versions -property:SemanticVersionIncrement=ReleaseLabel --version-suffix ${{ steps.suffix.outputs.value }}

    - uses: actions/upload-artifact@v4
      with:
        name: nuget
        if-no-files-found: error
        retention-days: 7
        path: ${{ github.workspace }}/nupkg/*.nupkg

  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      actions: write
    needs: [ create-nuget, run-tests ]

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_MULTILEVEL_LOOKUP: false

    steps:
    - uses: actions/download-artifact@v5
      with:
        name: nuget
        path: ${{ github.workspace }}/nupkg

    - name: Run local/dotnet-nuget-push-github@v1
      id: push-github
      working-directory: ${{ github.workspace }}/nupkg
      run: |
        dotnet nuget push *.nupkg --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
      
    # delete-artifact
    - uses: GeekyEggo/delete-artifact@v5
      if: ${{ steps.push-github.conclusion == 'success' }}
      with:
        name: nuget